---
settings:
  name: On-premises ONTAP clusters
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: 사내 ONTAP 클러스터 문서
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: 새로운 소식
      url: "/whats-new.html"
    - title: 알려진 제한 사항
      url: "/reference-limitations.html"
  - title: 시작하십시오
    entries:
    - title: 온프레미스 ONTAP 클러스터 관리에 대해 알아보십시오
      url: "/concept-onprem-ontap.html"
    - title: 사내 ONTAP 클러스터에 대해 알아보십시오
      url: "/task-discovering-ontap.html"
  - title: 온프레미스 ONTAP 클러스터를 관리합니다
    entries:
    - title: 검색된 클러스터를 직접 관리할 수 있습니다
      url: "/task-manage-ontap-direct.html"
    - title: Connector로 검색된 클러스터 관리
      url: "/task-manage-ontap-connector.html"
    - title: 클러스터 정보 및 계약 세부 정보를 봅니다
      url: "/task-view-cluster-info.html"
    - title: BlueXP 디지털 어드바이저를 사용하여 클러스터를 최적화합니다
      url: "/concept-aiq-digital-advisor.html"
    - title: 온프레미스 ONTAP 작업 환경을 제거합니다
      url: "/task-remove-on-prem.html"
  - title: 지식 및 지원
    entries:
    - title: 지원을 위해 등록하십시오
      url: "/task-support-registration.html"
    - title: 도움을 받으십시오
      url: "/task-get-help.html"
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
