---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, system manager, unsupported features 
summary: 알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오. 
---
= 알려진 제한 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
알려진 제한 사항은 이 제품 릴리스에서 지원하지 않거나 올바르게 상호 운용되지 않는 플랫폼, 장치 또는 기능을 식별합니다. 이러한 제한 사항을 주의 깊게 검토하십시오.



== ASA R2 시스템과 관련된 제한 사항

* ASA R2 시스템 검색은 전용 모드에서 BlueXP 를 사용할 때 지원되지 않습니다.
* NetApp ASA R2 시스템을 검색하고 작업 환경을 열면 바로 System Manager로 이동합니다.
+
ASA R2 시스템에서는 다른 관리 옵션을 사용할 수 없습니다. 표준 보기를 사용할 수 없으며 BlueXP 서비스를 활성화할 수 없습니다.



https://docs.netapp.com/us-en/asa-r2/index.html["ASA R2 시스템에 대해 자세히 알아보십시오"^]



== 지원되지 않는 클러스터입니다

SAML 인증으로 구성된 온프레미스 ONTAP 클러스터는 BlueXP에서 지원되지 않습니다.



== System Manager 제한 사항

다음 System Manager 기능은 BlueXP에서 지원되지 않습니다.

* 클러스터 설정
+
관리 IP 주소를 설정하고 온-프레미스 ONTAP 클러스터에서 admin 암호를 구성한 후 BlueXP에서 클러스터를 검색할 수 있습니다.

* 역할 기반 액세스 제어(커넥터만 해당)
+
커넥터를 사용하여 온프레미스 ONTAP 클러스터를 검색 및 관리할 때는 System Manager의 역할 기반 액세스 제어가 지원되지 않습니다. 검색 프로세스 중에 관리자 자격 증명을 입력하라는 메시지가 표시됩니다. 이러한 자격 증명은 System Manager에서 수행한 모든 작업에 사용됩니다.

+
직접 검색 옵션을 사용하면 작업 환경을 열 때마다 ONTAP 자격 증명으로 로그인하라는 메시지가 표시됩니다.

* BlueXP 백업 및 복구(클라우드 백업) 활성화
+
System Manager에서 BlueXP 백업 및 복구를 사용하려면 클러스터 버전이 9.13.1 이어야 합니다.

+
커넥터를 사용하여 클러스터를 _검색하지 않은 경우 System Manager(고급 보기)를 사용하여 백업 및 복구를 설정할 수 없습니다. 하지만 BlueXP에서 직접 온-프레미스 클러스터에서 백업 및 복구를 활성화할 수 있습니다. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["시작하는 방법을 알아보십시오"^]

* 온디맨드 업그레이드
+
클러스터 버전이 ONTAP 9.9.1 이하일 경우, 펌웨어 및 소프트웨어의 온디맨드 업그레이드를 사용할 수 없습니다.

+
커넥터가 없는 경우 로컬 컴퓨터에서 BlueXP를 사용하여 액세스할 수 있는 서버에서만 업데이트할 수 없습니다.

* 전체 검색
* 사용자 인터페이스 설정

