---
sidebar: sidebar 
permalink: task-discovering-ontap.html 
keywords: ontap, cluster, discover, manage, discovering, fas, aff, discover onprem, discover aff cluster, discover cluster, add cluster, active iq, digital wallet 
summary: BlueXP에서 제공되는 ONTAP 시스템 관리자를 사용하여 볼륨 관리를 시작하고 고급 관리를 수행할 수 있도록 BlueXP의 온프레미스 ONTAP 클러스터를 검색할 수 있습니다. 
---
= 사내 ONTAP 클러스터에 대해 알아보십시오
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP에서 제공되는 ONTAP 시스템 관리자를 사용하여 볼륨 관리를 시작하고 고급 관리를 수행할 수 있도록 BlueXP의 온프레미스 ONTAP 클러스터를 검색할 수 있습니다.



== 검색 및 관리 옵션

BlueXP는 사내 ONTAP 클러스터를 검색하고 관리하는 두 가지 방법을 제공합니다.

커넥터를 통한 검색:: 이 옵션을 사용하면 다음 기능을 사용하여 ONTAP 8.3 이상을 실행하는 클러스터를 관리할 수 있습니다.
+
--
* 기본 볼륨 작업을 제공하는 표준 보기입니다
* 시스템 관리자를 통해 관리 기능을 제공하는 고급 보기(ONTAP 9.10.0 이상에서 지원)
* 데이터 복제, 백업 및 복구, 데이터 분류 및 데이터 계층화를 제공하는 BlueXP 데이터 서비스와 통합


이 옵션을 사용하려면 Connector가 필요합니다. Connector를 클라우드 공급자 또는 사내에 설치할 수 있습니다.

--
직접 검색:: 이 옵션을 사용하면 시스템 관리자를 사용하여 ONTAP 9.12.1 이상을 실행하는 클러스터를 관리할 수 있습니다. 다른 관리 옵션은 사용할 수 없습니다. 표준 보기를 사용할 수 없으며 데이터 서비스를 설정할 수 없습니다.
+
--
이 옵션에는 커넥터가 필요하지 않습니다.

BlueXP 서비스에 연결하여 9.12.1 이상을 실행하는 사내 ONTAP 클러스터에서 System Manager에 액세스하면 BlueXP에서 직접 클러스터를 관리하라는 메시지가 표시됩니다. 이 프롬프트에 따라 직접 검색 옵션을 사용하여 BlueXP에서 클러스터를 검색합니다.

--


검색된 클러스터는 BlueXP Canvas에서 작업 환경으로 사용할 수 있습니다.

나중에 다른 검색 옵션을 사용하려는 경우 Canvas에서 내부 클러스터를 별도의 작업 환경으로 검색해야 합니다. 그러면 다른 작업 환경을 제거할 수 있습니다.



== 요구 사항

온프레미스 ONTAP 클러스터를 검색하기 전에 다음 요구사항을 충족하는지 확인하십시오.



=== 일반 요구 사항

* BlueXP를 시작해야 하며, 여기에는 로그인 및 계정 설정이 포함됩니다.
+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-overview.html["BlueXP를 시작하는 방법에 대해 알아보십시오"^]

* admin 사용자 계정의 클러스터 관리 IP 주소와 암호가 필요합니다.
* BlueXP는 HTTPS를 사용하여 ONTAP 클러스터를 검색합니다. 사용자 지정 방화벽 정책을 사용하는 경우 ONTAP 클러스터는 포트 443을 통한 인바운드 HTTPS 액세스를 허용해야 합니다.
+
기본 "관리" 방화벽 정책은 모든 IP 주소에서 인바운드 HTTPS 액세스를 허용합니다. 이 기본 정책을 수정하거나 자체 방화벽 정책을 만든 경우 HTTPS 프로토콜을 해당 정책에 연결하고 Connector 호스트에서 액세스를 활성화해야 합니다.





=== 커넥터 검색 및 관리에 대한 요구 사항

* 사내 클러스터에서 ONTAP 8.3 이상이 실행되고 있어야 합니다.
* Connector는 클라우드 공급자 또는 사내에 설치해야 합니다.
+
콜드 데이터를 클라우드에 계층화하려면 콜드 데이터를 계층화할 위치에 따라 Connector의 요구사항을 검토해야 합니다.

+
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["커넥터에 대해 자세히 알아보십시오"^]
** https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-managing-connectors.html["커넥터 간 전환"^]
** https://docs.netapp.com/us-en/cloud-manager-tiering/concept-cloud-tiering.html["Cloud Tiering에 대해 알아보십시오"^]


* 커넥터 호스트는 포트 443을 통한 아웃바운드 HTTPS 액세스를 허용해야 합니다.
+
Connector가 클라우드에 있는 경우 모든 아웃바운드 통신은 미리 정의된 보안 그룹에서 허용됩니다.





=== 직접 검색 및 관리 요구 사항

* 사내 클러스터에서 ONTAP 9.12.1 이상이 실행되고 있어야 합니다.
* 클러스터는 BlueXP 서비스에 대한 인바운드 및 아웃바운드 연결을 가져야 합니다.
+
https://cloudmanager.cloud.netapp.com/ontap-service/check-service-connection 으로 문의하십시오

* BlueXP 콘솔에 액세스하기 위해 사용 중인 컴퓨터는 사설 네트워크의 다른 리소스에 대한 연결을 제공하는 방법과 유사하게 사내 ONTAP 클러스터에 대한 네트워크 연결이 있어야 합니다.




== 클러스터 검색

BlueXP의 Canvas에서 온프레미스 ONTAP 클러스터를 검색할 수 있습니다. 검색 프로세스를 시작하면 BlueXP는 다음과 같이 클러스터를 검색합니다.

* ONTAP 클러스터에 연결된 활성 커넥터가 있는 경우 BlueXP는 해당 커넥터를 사용하여 클러스터를 검색하고 관리합니다.
* 커넥터가 없거나 커넥터가 ONTAP 클러스터에 연결되지 않은 경우 BlueXP는 직접 검색 및 관리 옵션을 자동으로 사용합니다.


.단계
. 탐색 메뉴에서 * Storage > Canvas * 를 선택합니다.
. Canvas 페이지에서 * 작업 환경 추가 * 를 클릭하고 * 온-프레미스 * 를 선택합니다.
. 온-프레미스 ONTAP 옆에 있는 * 검색 * 을 선택합니다.
. _Discover_페이지에서 클러스터 관리 IP 주소와 admin 사용자 계정의 암호를 입력합니다.
. 커넥터를 사용하지 않고 클러스터를 직접 검색하는 경우 * 자격 증명 저장 * 을 선택할 수 있습니다.
+
이 옵션을 선택하면 작업 환경을 열 때마다 자격 증명을 다시 입력할 필요가 없습니다. 이러한 자격 증명은 BlueXP 사용자와만 연결됩니다. 이 파일은 계정에 있는 다른 사람이 사용할 수 있도록 저장되지 않습니다.

. Discover * 를 선택합니다.


.결과
BlueXP는 클러스터를 검색하고 Canvas의 작업 환경으로 추가합니다. 이제 클러스터 관리를 시작할 수 있습니다.

* link:task-manage-ontap-direct.html["검색된 클러스터를 직접 관리하는 방법에 대해 알아보십시오"]
* link:task-manage-ontap-connector.html["Connector로 검색된 클러스터를 관리하는 방법에 대해 알아보십시오"]

